### ISSUE TITLE
`ddev solrctl` command error

### ISSUE THREAD

**Issue by maks-oleksyuk** [ddev/ddev-typo3-solr#4]
Hi, I get an error when trying to run the `ddev solrctl apply` command:

<img width="899" alt="image" src="https://github.com/ddev/ddev-typo3-solr/assets/90793591/f426ce04-9389-4bbf-b6cc-83538e3936d7">

ddev version v1.23.1

TYPO3 CMS 11.5.32 (Application Context: Development/DDEV) - PHP 8.1.28

 apache-solr-for-typo3/solr  11.5.3
 
 my config file:
 ```yml
 config: "app/web/typo3conf/ext/solr/Resources/Private/Solr/solr.xml"
configsets:
  - name: "ext_solr_11_5_0"
    path: "app/web/typo3conf/ext/solr/Resources/Private/Solr/configsets/ext_solr_11_5_0"
    cores:
      - name: "core_en"
        schema: "english/schema.xml"
      - name: "core_de"
        schema: "german/schema.xml"
      - name: "core_ar"
        schema: "arabic/schema.xml"
      - name: "core_bg"
        schema: "bulgarian/schema.xml"
      - name: "core_cs"
        schema: "czech/schema.xml"
      - name: "core_da"
        schema: "danish/schema.xml"
      - name: "core_el"
        schema: "greek/schema.xml"
      - name: "core_es"
        schema: "spanish/schema.xml"
      - name: "core_fi"
        schema: "finnish/schema.xml"
      - name: "core_fr"
        schema: "french/schema.xml"
      - name: "core_hu"
        schema: "hungarian/schema.xml"
      - name: "core_id"
        schema: "indonesian/schema.xml"
      - name: "core_it"
        schema: "italian/schema.xml"
      - name: "core_ja"
        schema: "japanese/schema.xml"
      - name: "core_ko"
        schema: "korean/schema.xml"
      - name: "core_lv"
        schema: "latvia/schema.xml"
      - name: "core_nl"
        schema: "dutch/schema.xml"
      - name: "core_no"
        schema: "norwegian/schema.xml"
      - name: "core_pl"
        schema: "polish/schema.xml"
      - name: "core_pt"
        schema: "portuguese/schema.xml"
      - name: "core_ro"
        schema: "romanian/schema.xml"
      - name: "core_rs"
        schema: "serbian/schema.xml"
      - name: "core_ru"
        schema: "russian/schema.xml"
      - name: "core_tr"
        schema: "turkish/schema.xml"
      - name: "core_uk"
        schema: "ukrainian/schema.xml"
      - name: "core_zh"
        schema: "chinese/schema.xml"
 ``` 
 
  System Version: macOS 12.7.5 (21H1222)
